// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABJtF467GWdoYfG510CStE4Q8H9yQu7-8',
    appId: '1:961372132821:web:028acc29cb5d02a887195c',
    messagingSenderId: '961372132821',
    projectId: 'accessable-e9ed2',
    authDomain: 'accessable-e9ed2.firebaseapp.com',
    storageBucket: 'accessable-e9ed2.appspot.com',
    measurementId: 'G-ZKVY0GQZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBik7wvZXe-8tNlwYL2givDt3mmOD799CA',
    appId: '1:961372132821:android:4a5baf25d6321c0b87195c',
    messagingSenderId: '961372132821',
    projectId: 'accessable-e9ed2',
    storageBucket: 'accessable-e9ed2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5nvzS1kWo9g84Pm1_obGaDrnBKO0g4v8',
    appId: '1:961372132821:ios:fc9caad0e6361eb487195c',
    messagingSenderId: '961372132821',
    projectId: 'accessable-e9ed2',
    storageBucket: 'accessable-e9ed2.appspot.com',
    iosBundleId: 'com.example.accessable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5nvzS1kWo9g84Pm1_obGaDrnBKO0g4v8',
    appId: '1:961372132821:ios:fc9caad0e6361eb487195c',
    messagingSenderId: '961372132821',
    projectId: 'accessable-e9ed2',
    storageBucket: 'accessable-e9ed2.appspot.com',
    iosBundleId: 'com.example.accessable',
  );
}
